name: Check

on:
  push:
    branches-ignore:
      - master

jobs:
    commit_lint:
      name: "Lint commit messages"
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: "Lint commit messages"
          uses: wagoid/commitlint-github-action@v1
          with:
            failOnWarnings: true
